### ISSUE TITLE
covid-19: container name to barcode (not lims id)

### ISSUE THREAD

**Issue by chichackles** [ctmrbio/claritylims#129]
PCR lab complain that printed barcode contains LIMS id. Should be container name.
The printing happens in

**Comment by boulund** [comment]
This is fixed, right? @chichackles

**Comment by chichackles** [comment]
It is fixed for now. I would like to revise how we generating this barcodes. They are extreme long. We have discussed with Maike, already, how to reduce them, but it will take some time and currently not urgent.

**Comment by boulund** [comment]
The main problem this issue refers to has been fixed. If we should revise the barcode generation code in the future we will open a new issue.
