### ISSUE TITLE
covid-19: Add ordering organization labportalen 

### ISSUE THREAD

**Issue by boulund** [ctmrbio/claritylims#165]
To add support for receiving samples from Labportalen, we need to add the labportalen organization URI to Clarity LIMS.

https://github.com/ctmrbio/claritylims/blob/prod/clarity-ext-scripts/clarity_ext_scripts/covid/partner_api_client.py#L27-L31

```
http://uri.d-t.se/id/Identifier/i-lab/labportalen
```

**Comment by chichackles** [comment]
The issue is resolved in dev branch. @MaeSei, please, test it on stage.

**Comment by boulund** [comment]
Validated
