### ISSUE TITLE
covid-19: Barcode size

### ISSUE THREAD

**Issue by MaeSei** [ctmrbio/claritylims#178]
Zebra printer barcodes are not big enough. The scanner in the robot fails to read them because of this.

**Comment by boulund** [comment]
This only concerns controls, or is it a general problem with all labels?

This should be a fairly easy fix regardless, the barcode printing code is located in https://github.com/ctmrbio/claritylims/blob/prod/clarity-ext-scripts/clarity_ext_scripts/covid/label_printer.py.

@MaeSei, Louise had an example of some ZPL code that generated barcodes of a suitable size for the controls?

**Comment by boulund** [comment]
Prototype from Lousie:

```

**Comment by boulund** [comment]
Summarizing the changes I need to make:

* First Field Origin: from `^FO7,5` to `^FO7,1` -- This is defined when initializing `ZebraLabelPrinterObject` in `create_printer`
* Barcode Field Default: from `^BY1,` to `^BY1.6,` -- This is defined when initializing `ZebraLabelPrinterObject` in `create_printer`
* Code 128 Barcode: from `^BCN,30,N` to `^BCN,48,N, ` -- This uses `info.height`
* Second Field Origin: from `^FO7,40` to `^FO7,55` -- These coordinates are computed as `second_row_offset = (7, info.height + 2*self.vertical_spacing)`
* Scalable bitmapped font: `A0,32,25` to `^A0,20,25` -- This is defined by `FONT_SIZES` and could in theory easily be tweaked, but  this affects `text_width` and `text_height` which are used when computing a lot of other values

**Comment by boulund** [comment]
There were issues with the new barcodes; different barcodes require different settings. There is no one-size-fits-all solution to barcode printing. 

We need to adjust the barcode printing code so it can pick a suitable `^BY` setting depending on which type of barcode is printed.

**Comment by boulund** [comment]
This issue is related to the fixes @chichackles wanted to do in #129

**Comment by boulund** [comment]
Merged to dev and prod
