### ISSUE TITLE
covid-19: DiagnosticReport.performer

### ISSUE THREAD

**Issue by boulund** [ctmrbio/claritylims#266]
> Kan ni lägga till lägga till information under DiagnosticReport.performer? 
> Det finns önskemål från bl.a. VGR att kunna se vem som utfört en analys. 

BGI:
```
{
  “resourceType”: “DiagnosticReport”,
   ...
  "performer": [
    {
      "reference": "Organization/l-5",
      "display": "NPC BGI"
    }
  ],
}
```

**Comment by boulund** [comment]
Waiting for validation on `stage02`

**Comment by MaeSei** [comment]
Validated on stage02

**Comment by boulund** [comment]
Awesome!
